[package]
name = "deno_gl"
version = "0.1.0"
authors = ["ReddikHaien <fredflug@online.no>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
deno_core = "0.87.0"
serde = "1.0.117"
winit = "0.25.0"
gl = "0.14.0"
raw-gl-context = "0.1.2"